server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: Kartikay#05
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          model: poolside/laguna-s-2.1:free
          temperature: 0.2


    

  
    
